# Generated by Django 4.1.7 on 2023-03-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Blog.image'),
        ),
    ]
