# Generated by Django 4.1.7 on 2023-03-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_bloginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
